# Generated by Django 3.0.3 on 2020-02-10 04:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2020, 2, 10, 4, 8, 57, 750197, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
