# Generated by Django 3.0.3 on 2020-02-14 05:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=datetime.datetime(2020, 2, 14, 5, 38, 10, 174442, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='upload',
            field=models.ImageField(default=datetime.datetime(2020, 2, 14, 5, 45, 18, 128342, tzinfo=utc), upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
