# Generated by Django 3.0.3 on 2020-02-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200216_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/'),
        ),
    ]
