# Generated by Django 3.0.4 on 2020-03-06 01:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2020, 3, 6, 1, 2, 13, 556129, tzinfo=utc), max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
