# Generated by Django 3.0.4 on 2020-03-08 00:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=datetime.datetime(2020, 3, 8, 0, 13, 34, 390805, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
